/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
"use client"

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes } = useGLTF('/create_the_foos_scale_0422080039_texture.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.mesh_0.geometry}
        material={nodes.mesh_0.material}
      />
    </group>
  )
}

useGLTF.preload('/create_the_foos_scale_0422080039_texture.glb')